### ISSUE TITLE
Revoking single line not working.

### ISSUE THREAD

**Issue by SolidTux** [EpicEricEE/typst-equate#2]
From looking at the tests, it looks like it should work to revoke a single line. But it currently still displays the number.

[Example](https://typst.app/project/r04BmuTC-_-UcKr8fJq0hA)

```typst
#import "@preview/equate:0.2.0": *

#set page(height: auto, margin: 1cm, width: 10cm)
#show: equate
#set math.equation(numbering: "(1.1)")

$
A =& B + C
\
=& C + D
$

$
A =& B + C
\
=& C + D
$ <equate:revoke>

$
A =& B + C #<equate:revoke> \
=& C + D
$
```

![grafik](https://github.com/user-attachments/assets/4ba49e66-4672-49c0-a619-d163f35c6dc1)

**Comment by SolidTux** [comment]
Ah, I just realized that this is a change that happened after the latest release. Would it be possible to make another one with this feature?

**Comment by EpicEricEE** [comment]
Done with typst/packages#957 :)

**Comment by SolidTux** [comment]
That was quick, thanks a lot!
