### ISSUE TITLE
How to left-align block equations?

### ISSUE THREAD

**Issue by beep-beep-beep-boop** [EpicEricEE/typst-equate#6]
Is there a way to left-align block equations when using equate? With the default typst equations, you can use `#align`, but that doesn't seem to work with equate.

**Comment by EpicEricEE** [comment]
I wasn't even aware that wrapping with `align` works for default equations. As far as I know, the intended way is
```typ
#show math.equation: set align(left)
```
which also works with this package.

**Comment by beep-beep-beep-boop** [comment]
thank you!
